'use client'

// import type { Metadata } from "next";
import {Inter, Suez_One, Roboto_Slab, Roboto} from 'next/font/google'
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const inter = Inter({
  subsets: ['latin'],
  weight: ['300'],
  style: ['normal'],
  variable: '--font-inter'
})

const suezOne = Suez_One({
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal'],
  variable: '--font-suze-one'
})

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300'],
  style: ['normal'],
  variable: '--font-roboto'
})

const robotoSlab = Roboto_Slab({
  subsets: ['latin'],
  weight: ['300'],
  style: ['normal'],
  variable: '--font-roboto-slab'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${suezOne.variable} ${roboto.variable} ${robotoSlab.variable}`}>
        {children}
      </body>
    </html>
  );
}
