import type { Metadata } from "next";
import {Inter, Suez_One, Roboto_Slab, Roboto} from 'next/font/google'
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const inter = Inter({
  subsets: ['latin'],
  weight: ['300'],
  style: ['normal']
})

export const suezOne = Suez_One({
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal']
})

export const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300'],
  style: ['normal']
})

export const robotoSlab = Roboto_Slab({
  subsets: ['latin'],
  weight: ['300'],
  style: ['normal']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
